
create table if not exists public.chapters (
  id bigint generated by default as identity primary key,
  number integer not null unique,
  title text not null,
  description text default '',
  cover_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.chapter_pages (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null references public.chapters(id) on delete cascade,
  page_number integer not null,
  image_url text not null,
  created_at timestamptz not null default now(),
  unique(chapter_id, page_number)
);

alter table public.chapters enable row level security;
alter table public.chapter_pages enable row level security;

create policy "Public can read chapters"
on public.chapters for select
to anon, authenticated
using (true);

create policy "Public can read pages"
on public.chapter_pages for select
to anon, authenticated
using (true);

-- Admin writes should be performed with Supabase Auth + server-side/secure policies.
-- Do NOT paste a service_role key into the browser.
